name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libssl-dev libgtest-dev

    - name: Build project
      run: |
        make

    - name: Run C++ tests
      run: |
        make test-block
        make test-blockchain
        make test-wallet
        make test-crypto

  test-javascript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install JavaScript dependencies
      run: |
        cd api/javascript
        npm install

    - name: Build JavaScript client
      run: |
        cd api/javascript
        npm run build

    - name: Run JavaScript tests
      run: |
        cd api/javascript
        npm test